---
# Image hashes in this file are for amd64 systems
# NB: paths relative to the `server/build` directory, which contains the original compose file that this yaml is overriding
version: '2.4'
services:

  server:
    image: "${SERVER_IMAGE}"
    restart: always
    env_file:
      - "../../e2e-tests/.ci/.env.server"
    environment:
      ### Required variables - start
      # MM_LICENSE: "..."   # NB, OPTIONAL
      ### Required variables - end
      MM_SERVICESETTINGS_SITEURL: "http://server:8065"
      MM_SERVICESETTINGS_ENABLELOCALMODE: "true"
      MM_PLUGINSETTINGS_ENABLED: "true"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_PLUGINSETTINGS_AUTOMATICPREPACKAGEDPLUGINS: "true"
      MM_TEAMSETTINGS_ENABLEOPENSERVER: "true"
      MM_ELASTICSEARCHSETTINGS_CONNECTIONURL: "true"
      MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10&binary_parameters=yes"
      MM_SQLSETTINGS_DRIVERNAME: "postgres"
      MM_LDAPSETTINGS_LDAPSERVER: "openldap"
      MM_EMAILSETTINGS_SMTPSERVER: "inbucket"
      MM_CLUSTERSETTINGS_READONLYCONFIG: "false"
      MM_FEATUREFLAGS_USECASEONBOARDING: "false"
      # TODO added by me, check before merging the PR
      MM_SERVICESETTINGS_ENABLEONBOARDINGFLOW: "false"
      MM_FEATUREFLAGS_ONBOARDINGTOURTIPS: "false"
      MM_LICENSE: "${MM_LICENSE}"
    ports:
      - "8065:8065"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      inbucket:
        condition: service_healthy
      openldap:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      keycloak:
        condition: service_healthy
      dejavu:
        condition: service_healthy
      prometheus:
        condition: service_healthy
      grafana:
        condition: service_healthy
      webhook-interactions:
        condition: service_healthy

  webhook-interactions:
    image:  public.ecr.aws/q3m3k0p4/mattermost-build-webapp:20220802_node-16.10.0
    command: sh -c "npm install -g axios express client-oauth2@larkox/js-client-oauth2#e24e2eb5dfcbbbb3a59d095e831dbe0012b0ac49 && exec node webhook_serve.js"
    environment:
      NODE_PATH: /usr/local/lib/node_modules/
    healthcheck:
      test: [ "CMD", "curl", "-s", "-o/dev/null", "127.0.0.1:3000" ]
      interval: 5s
      timeout: 10s
      retries: 3
    working_dir: /cypress
    volumes:
      - "../../e2e-tests/cypress/:/cypress:ro"
    networks:
      default:
        aliases:
          - webhook-interactions

  # TODO use gitlab actions' matrix directive to parallelize the jobs
  # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix
  cypress:
    image: "public.ecr.aws/mattermostqa/cypress-browsers-public:node16.14.2-slim-chrome100-ff99-edge"
    entrypoint: [ "/bin/bash", "-c" ]
    command: [ "until [ -f /var/run/mm_terminate ]; do sleep 5; done" ]
    env_file:
      - "../../e2e-tests/.ci/.env.cypress"
      - "../../e2e-tests/.ci/.env.dashboard"
    environment:
      ### Required variables - start
      # BRANCH: "..."
      # BUILD_ID: "..."
      # AUTOMATION_DASHBOARD_URL: "..."
      # AUTOMATION_DASHBOARD_TOKEN: "..."
      ### Required variables - end
      REPO: "mattermost-server"
      CI_BASE_URL: "localhost-${MM_NODE_INDEX}"
      # Cypress configuration
      BROWSER: "chrome"
      HEADLESS: "true"
      CYPRESS_baseUrl: "http://server:8065"
      CYPRESS_dbConnection: "postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10"
      CYPRESS_elasticsearchConnectionURL: "http://elasticsearch:9200"
      CYPRESS_keycloakBaseUrl: "http://keycloak:8484"
      CYPRESS_ldapServer: "openldap"
      CYPRESS_minioS3Endpoint: "minio:9000"
      CYPRESS_smtpUrl: "http://inbucket:9001"
      CYPRESS_webhookBaseUrl: "http://webhook-interactions:3000"
      CYPRESS_chromeWebSecurity: "false"
      CYPRESS_firstTest: "true"
      CYPRESS_resetBeforeTest: "true"
      CYPRESS_runLDAPSync: "true"
      CYPRESS_allowedUntrustedInternalConnections: "localhost webhook-interactions"
      CYPRESS_serverEdition: E20
      # disable shared memory X11 affecting Cypress v4 and Chrome
      # https://github.com/cypress-io/cypress-docker-images/issues/270
      QT_X11_NO_MITSHM: "1"
      _X11_NO_MITSHM: "1"
      _MITSHM: "0"
      # avoid too many progress messages
      # https://github.com/cypress-io/cypress/issues/1243
      CI: "1"
      # TODO possibly a node image upgrade could fix this
      PATH: /app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    working_dir: /app
    volumes:
      - "../../e2e-tests/cypress/:/app"
