codecov:
  ci:
    - build.mattermost.com
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        threshold: 1%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch: off
    changes: no
ignore:
  - store/storetest
comment: false
