version: '2.4'
services:
  elasticsearch:
    restart: 'no'
    container_name: mattermost-elasticsearch
    platform: "linux/x86_64"
    ports:
      - "9200:9200"
      - "9300:9300"
    extends:
        file: build/docker-compose.common.yml
        service: elasticsearch