version: '3.4'
services:
  mysql:
    container_name: mattermost-mysql
    ports:
      - "3306:3306"
  postgres:
    container_name: mattermost-postgres
    ports:
      - "5432:5432"
  minio:
    container_name: mattermost-minio
    ports:
      - "9000:9000"
  inbucket:
    container_name: mattermost-inbucket
    ports:
      - "10025:10025"
      - "10080:10080"
      - "10110:10110"
  openldap:
    container_name: mattermost-openldap
    ports:
      - "389:389"
      - "636:636"
  elasticsearch:
    container_name: mattermost-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  redis:
    container_name: mattermost-redis
    ports:
      - "6379:6379"
  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - mm-test
    depends_on:
      - mysql
      - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
      - redis
    command: postgres:5432 mysql:3306 minio:9000 inbucket:10080 openldap:389 elasticsearch:9200 redis:6379

networks:
  mm-test:
    driver: bridge
