services:
  mysql:
    container_name: mattermost-mysql
    ports:
      - "3306:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql
  mysql-read-replica:
    container_name: mattermost-mysql-read-replica
    ports:
      - "3307:3306"
    extends:
        file: build/docker-compose.common.yml
        service: mysql-read-replica

  start_dependencies:
    image: mattermost/mattermost-wait-for-dep:latest
    networks:
      - mm-test
    depends_on:
      - mysql
      - postgres
      - minio
      - inbucket
      - openldap
      - elasticsearch
      - opensearch
      - prometheus
      - grafana
      - loki
      - promtail
    command: postgres:5432 mysql:3306 minio:9000 inbucket:9001 openldap:389 elasticsearch:9200 opensearch:9201 prometheus:9090 grafana:3000 loki:3100 promtail:3180
