name: API

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version-file: .nvmrc
        cache: 'npm'
        cache-dependency-path: api/package-lock.json
    - name: Run build
      run: |
        make build

    - uses: actions/upload-artifact@v2
      with:
        name: mattermost-api-reference
        path: api/v4/html
