# TODO move these modifications to the normal smoketests job, and comment out the extra OSes
#      Put here only for iterating faster, using a static image
name: E2E Tests MultiOS
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  smoketests:
    strategy:
      matrix:
        # NB: only macos-12 is supported as of today
        os: [windows-2022, macos-12]
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        working-directory: e2e-tests
    env:
      SERVER_IMAGE: mattermost/mattermost-team-edition:8.1.2
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-macos-docker
        if: runner.os == 'macos'
        run: |
          brew install docker docker-compose
          colima start
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
          # https://github.com/abiosoft/colima/blob/main/docs/FAQ.md#cannot-connect-to-the-docker-daemon-at-unixvarrundockersock-is-the-docker-daemon-running
          sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
      - name: ci/windows-envdump
        if: runner.os == 'windows'
        run: env
        shell: bash.exe
      - name: ci/e2e-smoketests
        run: |
          make
        shell: bash${{ runner.os == 'windows' && '.exe' || '' }}
      - name: ci/e2e-smoketests-store-results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: e2e-smoketests-results
          path: |
            e2e-tests/cypress/logs/
            e2e-tests/cypress/results/
      - name: ci/e2e-smoketests-assert-results-${{ matrix.os }}
        run: |
          # Assert that the run contained 0 failures
          CYPRESS_FAILURES=$(find cypress/results -name '*.json' | xargs -l jq -r '.stats.failures' | jq -s add)
          echo "Cypress run completed with $CYPRESS_FAILURES failures"
          [ "$CYPRESS_FAILURES" = "0" ]
