name: E2E Tests MultiOS
on:
  push:

defaults:
  run:
    shell: bash

jobs:
  smoketests:
    strategy:
      matrix:
        os: [windows-2022, macos-13]
    runs-on: "${{ matrix.os }}"
    defaults:
      run:
        working-directory: e2e-tests
    steps:
      - name: Setup docker (missing on MacOS)
        if: runner.os == 'macos'
        run: |
          brew install docker docker-compose
          colima start
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/e2e-smoketests
        env:
          SERVER_IMAGE: mattermost/mattermost-team-edition:8.1.2
        run: |
          make
      - name: ci/e2e-smoketests-store-results
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: e2e-smoketests-results
          path: |
            e2e-tests/cypress/logs/
            e2e-tests/cypress/results/
      - name: ci/e2e-smoketests-assert-results-${{ matrix.os }}
        run: |
          # Assert that the run contained 0 failures
          CYPRESS_FAILURES=$(find cypress/results -name '*.json' | xargs -l jq -r '.stats.failures' | jq -s add)
          echo "Cypress run completed with $CYPRESS_FAILURES failures"
          [ "$CYPRESS_FAILURES" = "0" ]
