name: E2E Tests
on:
  workflow_dispatch:
    inputs:
      payload:
        description: "The triggerer payload"
        required: true
        type: string

defaults:
  run:
    shell: bash
jobs:
  expose-incoming-variables:
    runs-on: ubuntu-22.04
    outputs:
      repository_full_name: ${{ env.TRIGGERER_REPO_FULL_NAME }}
      commit_sha: ${{ env.TRIGGERER_COMMIT_SHA }}
    steps:
      - uses: mattermost/actions/release/expose-events-vars@f04d8cc6fbd215659c3406974a74f7167c00803a
        with:
          payload: ${{ inputs.payload }}
  cypress-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: e2e-tests/cypress
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        id: setup_node
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: 'e2e-tests/cypress/package-lock.json'
      - name: ci/cypress/npm-install
        run: |
          npm ci
      - name: ci/cypress/npm-check
        run: |
          npm run check
  playwright-check:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: e2e-tests/playwright
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: ci/setup-node
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        id: setup_node
        with:
          node-version-file: ".nvmrc"
          cache: npm
          cache-dependency-path: 'e2e-tests/playwright/package-lock.json'
      - name: ci/get-webapp-node-modules
        working-directory: webapp
        # requires build of client and types
        run: |
          make node_modules
      - name: ci/playwright/npm-install
        run: |
          npm ci
      - name: ci/playwright/npm-check
        run: |
          npm run check
  smoketests:
    runs-on: ubuntu-22.04
    needs:
      - cypress-check
      - playwright-check
    defaults:
      run:
        working-directory: e2e-tests
    steps:
      - name: ci/checkout-repo
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          repository: ${{ needs.expose-incoming-variables.outputs.repository_full_name }}
          ref: ${{ needs.expose-incoming-variables.outputs.commit_sha }}
      - name: ci/e2e-smoketests
        run: |
          make
          # Assert that the run contained 0 failures
          CYPRESS_FAILURES=$(find cypress/results -name '*.json' | xargs -l jq -r '.stats.failures' | jq -s add)
          echo "Cypress run completed with $CYPRESS_FAILURES failures"
          [ "$CYPRESS_FAILURES" = "0" ]
