name: Server CI PR
on:
  pull_request:
env:
  go-version: "1.19.5"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# This file just imports the template yml
# and runs it with concurrency. We have to do this in this way
# because the concurrency label cannot be added conditionally
# and it _always_ cancels pending workflows. So master CI builds
# always kept getting canceled.

jobs:
  pr-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: mattermost/actions/delivery/update-commit-status@a74f6d87f847326c04d326bf1908da40cb9b3556
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repository_full_name: mattermost/mattermost
          commit_sha: ${{ github.event.pull_request.head.sha }}
          context: potato
          description: "yes"
          status: success
