# Base CI template which is called from server-ci-pr.yml
# and server-ci-master.yml

name: Server CI Template
on:
  workflow_call:

env:
  go-version: "1.19.5"

jobs:
  test-postgres-normal:
    name: Postgres
    uses: ./.github/workflows/server-test-template.yml
    with:
      name: Postgres
      datasource: postgres://mmuser:mostest@postgres:5432/mattermost_test?sslmode=disable&connect_timeout=10
      drivername: postgres
      logsartifact: postgres-server-test-logs
    secrets: inherit
