name: Tag Public Module

on:
  workflow_dispatch:
    inputs:
      semver_bump:
        type: string
        required: false
        default: patch # https://github.com/actions-ecosystem/action-bump-semver/tree/34e334551143a5301f38c830e44a22273c6ff5c5/#inputs
      commit_sha:
        type: string
        required: false

jobs:
  tag-public-module:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: release/checkout-mattermost
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ inputs.commit_sha || github.ref_name }}
          fetch-depth: 0

      - name: release/find-latest-public-module-tags
        run: |
          echo LATEST_MODULE_TAG=$(git tag --list 'server/public/*' --format='%(refname:lstrip=-1)'  --sort -v:refname | head -1) >> ${GITHUB_ENV}

      - name: release/generate-module-release-notes
        run: |
          git log --oneline --graph --decorate --abbrev-commit server/public/${{ env.LATEST_MODULE_TAG }}...$(git rev-parse HEAD) server/public
          echo "RELEASE_NOTES<<EOF" >> ${GITHUB_ENV}
          echo '$(git log --oneline --graph --decorate --abbrev-commit server/public/${{ env.LATEST_MODULE_TAG }}...$(git rev-parse HEAD) server/public)' >> ${GITHUB_ENV}
          echo "EOF" >> ${GITHUB_ENV}

      - name: release/semver-bump
        uses: actions-ecosystem/action-bump-semver@34e334551143a5301f38c830e44a22273c6ff5c5 # v1.0.0
        id: bump-semver
        with:
          current_version: ${{ env.LATEST_MODULE_TAG }}
          level: ${{ inputs.semver_bump }}

      - name: release/create-tag
        uses: actions-ecosystem/action-push-tag@6e82caefe706f5a729e354df7443dc82f98a414f # v1.0.0
        with:
          tag: "server/public/${{ steps.bump-semver.outputs.new_version }}"
          message: ${{ env.RELEASE_NOTES }}
